export enum Permission {
  PRODUCT_MANAGE = 'PRODUCT_MANAGE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
}
