export default () => ({
  auth: {
    JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: '600s',
    JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: '10000s',
  },
});
